In [ ]:
This notebook demonstrates how to add categorical variables with lirbary code. To extend to all of the variables,
just edit the ``lib/category_maps.csv`` file. The ``

In [11]:
%load_ext autoreload
%autoreload 1
import sys; sys.path.append("..")
%aimport lib.util
from lib.util import reformat_tract, add_race_eth, add_purpose_type, add_income_group, add_all_category_columns
import pandas as pd
import numpy as np
from ambry import library

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
l = library()
p = l.get('ffiec.gov-hmda-2010e-lar-2012-ca').partition
df = p.select("SELECT * FROM lar WHERE county_code = 73").pandas

In [14]:
add_race_eth(df) # Adds race_eth column
add_purpose_type(df) # Adds purpose_type column Combines loan_purpose and loan_type in the same way as the summary report
add_income_group(df) # Adds income_group column

In [19]:
# Add '_c' categorical columns
from lib.util import add_all_category_columns
add_all_category_columns(df)

Adding category column for  income_group
Adding category column for  loan_type
Adding category column for  loan_purpose
Adding category column for  race_eth

In [23]:
df[['loan_type', 'loan_type_c', 'loan_purpose', 'loan_purpose_c']]

        loan_type   loan_type_c  loan_purpose    loan_purpose_c
0               1  Conventional             3       Refinancing
1               1  Conventional             3       Refinancing
2               1  Conventional             3       Refinancing
3               1  Conventional             2  Home Improvement
4               1  Conventional             2  Home Improvement
5               1  Conventional             1     Home Purchase
6               1  Conventional             1     Home Purchase
7               1  Conventional             3       Refinancing
8               1  Conventional             1     Home Purchase
9               1  Conventional             1     Home Purchase
10              1  Conventional             1     Home Purchase
11              1  Conventional             1     Home Purchase
12              1  Conventional             3       Refinancing
13              1  Conventional             3       Refinancing
14              1  Conventional             2  Home Improvement
15              1  Conventional             3       Refinancing
16              1  Conventional             3       Refinancing
17              1  Conventional             1     Home Purchase
18              1  Conventional             3       Refinancing
19              1  Conventional             3       Refinancing
20              1  Conventional             3       Refinancing
21              1  Conventional             3       Refinancing
22              1  Conventional             3       Refinancing
23              1  Conventional             3       Refinancing
24              1  Conventional             3       Refinancing
25              1  Conventional             3       Refinancing
26              1  Conventional             3       Refinancing
27              1  Conventional             3       Refinancing
28              1  Conventional             2  Home Improvement
29              1  Conventional             3       Refinancing
...           ...           ...           ...               ...
242753          1  Conventional             1     Home Purchase
242754          1  Conventional             1     Home Purchase
242755          1  Conventional             1     Home Purchase
242756          1  Conventional             1     Home Purchase
242757          1  Conventional             1     Home Purchase
242758          1  Conventional             1     Home Purchase
242759          1  Conventional             1     Home Purchase
242760          1  Conventional             1     Home Purchase
242761          1  Conventional             1     Home Purchase
242762          1  Conventional             1     Home Purchase
242763          1  Conventional             1     Home Purchase
242764          1  Conventional             1     Home Purchase
242765          1  Conventional             1     Home Purchase
242766          1  Conventional             1     Home Purchase
242767          1  Conventional             1     Home Purchase
242768          1  Conventional             1     Home Purchase
242769          1  Conventional             2  Home Improvement
242770          1  Conventional             1     Home Purchase
242771          1  Conventional             1     Home Purchase
242772          2           FHA             1     Home Purchase
242773          3            VA             3       Refinancing
242774          1  Conventional             3       Refinancing
242775          1  Conventional             3       Refinancing
242776          1  Conventional             3       Refinancing
242777          1  Conventional             3       Refinancing
242778          1  Conventional             3       Refinancing
242779          1  Conventional             3       Refinancing
242780          1  Conventional             3       Refinancing
242781          1  Conventional             3       Refinancing
242782          1  Conventional             3       Refinancing

[242783 rows x 4 columns]